CREATE SEQUENCE DEPT_S
SELECT *
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME='DEPT_S';

CREATE TABLE DEPT_TEST_S (
    DEENC NUMBER PRIMARY KEY,
    DNAME VARCHAR2 (100)
) INSERT INTO DEPT_TEST_S ( DEPNO, DNAME) 
VALUES (DEPT_S.NEXTVAL, 'Sales');

SELECT DEPT_S.CURRVAL
FROM DUAL;

SELECT DEPT_S.NEXTVAL
FROM DUAL;

INSERT INTO DEPT_TEST_S ( DEPNO, DNAME)
VALUES ( DEPT_S.NEXTVAL, 'IT');

CREATE SEQUENCE DEPT S1
START WITH 10
INCREMENT BY 20
SELECT FROM USER_SEQUENCES
WHERE SEQUENCE_NAME='DEPT_S1';

INSERT INTO DEPT_TEST_S ( DEPNO, DNAME) 
VALUES ( DEPT S1.NEXTVAL, 'Marketing');

INSERT INTO DEPT_TEST_S ( DEPNO, DNAME)
VALUES ( DEPT_S1.NEXTVAL, 'Help Desk');

DROP SEQUENCE DEPT_S2;

CREATE SEQUENCE DEPT_S2 INCREMENT BY -5;

SELECT *
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME='DEPT_S2' 
INSERT INTO DEPT_TEST_S ( DEPNO, DNAME ) 
VALUES ( DEPT_S2.NEXTVAL, 'Marketing' );

INSERT INTO DEPT_TEST_S ( DEPNO, DNAME)
VALUES ( DEPT_S2.NEXTVAL, 'Help Desk');

UPDATE DEPT_TEST_S
SET DEENO = DEPT_S2.NEXTVAL;

--=============================================================
CREATE SEQUENCE EMP S;

CREATE TABLE EMP (
    EMPID NUMBER DEFAULT EMP S.NEXTVAL PRIMARY KEY NAME VARCHAR2(100),
    DEPTNO NUMBER
);

INSERT INTO DEPT_TEST_S ( DEPNO, DNAME)
VALUES ( DEPT S.NEXTVAL, 'support');

INSERT INTO EMP ( NAME, DEPTNO)
VALUES ( 'ali', DEPT_S.CURRVAL);

INSERT INTO EMP ( NAME, DEPTNO)
VALUES ('ahmed', DEPT S.CURRVAL);

INSERT INTO EMP ( NAME,DEPTNO) 
VALUES ( 'samer', DEPT_S.CURRVAL);

--=============================================================
--=============================================================
--=============================================================
--Creating Private SYNONYM E for EMPLOYEES table
CREATE SYNONYM E
FOR EMPLOYEES;

--so you can use the SYNONYM now to call the table
SELECT *
FROM E;

--THE SYNONYM INFO IN DICTIONARY VIEW CALLED USER_SYNONYMS/ ALL_SYNONYMS

SELECT *
FROM USER_SYNONYMS;

--YOU CAN DROP THE SYNONYM
DROP SYNONYM ÎE;